[package]
name = "ci2"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"

machine-vision-formats = { path = "../machine-vision-formats" }
ci2-types = {path="ci2-types"}
