[package]
name = "bui-backend-session"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
log = "0.4"
futures = "0.3"
hyper = {version="0.13.0", default-features = false, features=["tcp"]}
parking_lot = "0.11"
http = "0.2"
bytes = "0.6"
serde = "1"
cookie = "0.14"

bui-backend-types = "0.8"
