[workspace]
members = [
    "ads-webasm",
    "apriltag",
    "basic-frame",
    "bg-movie-writer",
    "bisection-search",
    "braid",
    "braid/braid-run",
    "braid-offline",
    "braidz-parser",
    "braidz-parser/braidz-cli",
    "braidz-types",
    "bui-backend-session",
    "bui-backend-session/demo",
    "camcal",
    "camtrig",
    "camtrig-comms",
    "ci2",
    "ci2/ci2-types",
    "ci2-async",
    "ci2-cli",
    "ci2-dc1394",
    "ci2-flycap2",
    "ci2-pylon",
    "ci2-pyloncxx",
    "ci2-remote-control",
    "ci2-simple-async-demo",
    "ci2-simple-demo",
    "convert-image",
    "crossbeam-ok",
    "csv-eof",
    "datetime-conversion",
    "dc1394",
    "download-verify",
    "enum-iter",
    "env-tracing-logger",
    "fastimage",
    "fly-eye",
    "flycap2",
    "fmf",
    "fmf/fmf-cli",
    "flydra-mvg",
    "flydra-mvg/flydra-mvg-fuzz-target",
    "flydra-types",
    "flydra1-triggerbox-rs",
    "flydra2",
    "flydra2-mainbrain",
    "freemovr-calibration",
    "freemovr-calibration/freemovr-calibration-cli",
    "groupby",
    "gst-plugin-apriltag",
    "gst-plugin-nvargustime",
    "http-video-streaming",
    "http-video-streaming/http-video-streaming-types",
    "image-tracker",
    "image-tracker/image-tracker-types",
    "image-tracker/im-pt-detect-config",
    "imagesrc",
    "imagesrc-gst",
    "lstsq",
    "machine-vision-formats",
    "machine-vision-shaders",
    "mvg",
    "mvg/mvg-util",
    "ncollide-geom",
    "nvenc",
    "nvenc/dynlink-cuda",
    "nvenc/dynlink-nvidia-encode",
    "nvenc/dynlink-nvidia-encode/gen-nvenc-bindings",
    "opencv-calibrate",
    "opencv-calibrate/find-chessboard",
    "plugin-defs",
    "posix-scheduler",
    "py-strandcam/rust",
    "pylon",
    "pylon/pylon-simple-record",
    "pylon-cxx-rs",
    "refraction",
    "rt-image-viewer",
    "rt-image-viewer/storetype",
    "select",
    "simple-frame",
    "simple-obj-parse",
    "strand-cam",
    "strand-cam-csv-config-types",
    "strand-cam-mkvfix",
    "strand-cam-offline-kalmanize",
    "strand-cam-pseudo-cal",
    "strand-cam-storetype",
    "timestamped-frame",
    "tracking",
    "ufmf",
    "webm-writer",
    "withkey",
    "zip-or-dir",
]

exclude = [
    "ANCIENT",
    "camtrig-firmware",
    "ci2-aravis", # Exclude for now until we can update it
    "pyci2/extensions", # Exclude for now because setuptools_rust doesn't find built product.
]

[profile.release]
debug = true

# [replace]
# "tokio-threadpool:0.1.6" = {git="https://bare-git.strawlab.org/tokio.git", rev="472e64c1ea67f3976191cb1b291061faf2082735"}

[patch.crates-io]
webm = { git = "https://bare-git.strawlab.org/rust-webm.git", rev="9f9d158031bd5bc465ff6b40103575fb8ed742aa"}
cbindgen = {git="https://github.com/astraw/cbindgen", rev="7279a4faceec28593bd8a6b0192fd3ac3ee25b53"} # until https://github.com/eqrion/cbindgen/pull/304
yew-tincture = {git="https://drandrewstraw@dev.azure.com/drandrewstraw/yew-tincture/_git/yew-tincture", rev="e835164fa9ced144811b314625a1df43759ea3e7"}
mini-rxtx = {git="https://bare-git.strawlab.org/mini-rxtx.git", rev="d8f9b7902aae8c2e69a3262ccf70fde31a2011ee"}
tokio-serial = {git="https://github.com/mnbbrown/tokio-serial", rev="ace64363030f8af6b5c9aaadd930ee9515fe33f1"}
