[package]
name = "flydra-types"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
byteorder = "1"
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
failure_derive = "0.1"
serde = {version="1.0", features=["derive"]}
serde_cbor = "0.9"
tokio-util = {version="0.4", features=["codec"]}
bytes = "0.5"
bitflags = "1.0"
dns-lookup = {version="1", optional=true}
ordered-float = {version="1", features=["serde"]}
static_assertions = "0.3"
bui-backend-types = "0.8"

withkey = {path="../withkey"}
datetime-conversion = {path="../datetime-conversion"}
rust-cam-bui-types = {path="../rust-cam-bui-types"}

[features]
with-dns=["dns-lookup"]
