[package]
name = "ufmf"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
byteorder = "1.1"
chrono = "0.4"
thiserror = "1.0"
structure = "0.1.2"
cast = "0.2.2"

machine-vision-formats = { path = "../machine-vision-formats" }
timestamped-frame = { path = "../timestamped-frame" }
datetime-conversion = {path="../datetime-conversion"}

[dev-dependencies]
basic-frame = {path="../basic-frame"}
