[package]
name = "braid-frontend"
version = "0.8.2" # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# Bypass (for now) build errors when this is in the workspace below me.
[workspace]
members = []

[dependencies]
seed = "0.5.1"
wasm-bindgen = "0.2.45"
web-sys = {version="0.3", features=["console", "EventSource", "MessageEvent",
    "DateTimeValue", "HtmlInputElement", "Element", "Window", "Document",
    "Location"]}
js-sys = "0.3.28"
serde = { version = "1.0.85", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
failure = "0.1"
wee_alloc = "0.4.5"
futures = "0.3"
chrono = "0.4.9"

uuid = {version="0.8", features=["wasm-bindgen"]}

enum-iter = {path="../../enum-iter"}
flydra-types = {path="../../flydra-types"}
rust-cam-bui-types = {path="../../rust-cam-bui-types"}
