[package]
name = "braid-frontend"
version = "0.9.0" # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# Bypass (for now) build errors when this is in the workspace below me.
[workspace]
members = []

[dependencies]
anyhow = "1.0"
log = "0.4"
wasm-logger = "0.2.0"
wasm-bindgen = "0.2.58"
web-sys = {version="0.3", features=["Window"]}
yew = "0.17.4"
serde = { version = "1.0.85", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

uuid = {version="0.8", features=["wasm-bindgen"]}
yew-event-source = "0.1"

flydra-types = {path="../../flydra-types", default-features=false}
rust-cam-bui-types = {path="../../rust-cam-bui-types"}
ads-webasm = {path="../../ads-webasm"}

[patch.crates-io]
yew-tincture = {git="https://drandrewstraw@dev.azure.com/drandrewstraw/yew-tincture/_git/yew-tincture", rev="e835164fa9ced144811b314625a1df43759ea3e7"}
