[package]
name = "braid-offline"
version = "0.9.0" # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.5", features = ["release_max_level_debug"] }
structopt = "0.3"
thiserror = "1.0"
anyhow = "1.0"
csv = "1.1"
serde = {version="^1.0", features=["derive"]}
toml = "0.5"
itertools = "0.8"
chrono = "0.4"
futures = "0.3"
crossbeam-channel = "0.5"
stream-cancel = "0.8"

env-tracing-logger = {path="../env-tracing-logger"}
csv-eof = {path="../csv-eof"}
flydra2 = {path="../flydra2", default-features=false, features=["bundle_files"]}
flydra-types = {path="../flydra-types"}
groupby = {path="../groupby"}
tokio = {version="1.0.1", default-features=false, features=["rt-multi-thread","macros"]}
zip-or-dir = {path="../zip-or-dir"}
flydra-mvg = {path="../flydra-mvg"}
braidz-parser = {path="../braidz-parser"}

[dev-dependencies]
download-verify = {path="../download-verify"}
tempfile = "3"
zip = { version = "0.5", default-features = false, features=["time"] }
approx = "0.4"
env_logger = "0.8"
fs_extra = "1.1"

[features]
default = ["full-3d"]

flat-3d = ["flydra2/flat-3d"]
full-3d = ["flydra2/full-3d"]

backtrace = ["zip-or-dir/backtrace", "flydra2/backtrace"]
