[package]
name = "braidz-viewer"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# Bypass (for now) build errors when this is in the workspace below me.
[workspace]
members = []

[dependencies]
bytesize = "1.0"
log = "0.4"
wasm-logger = "0.2.0"

yew = "0.17.4"

wasm-bindgen = "^0.2.45"
web-sys = {version="^0.3.28", features=["Blob", "DateTimeValue", "File",
    "FileList", "FileReader", "HtmlInputElement"]}
js-sys = "0.3.28"
plotters = "0.3"
plotters-canvas = "0.3"
wee_alloc = "0.4.5"
serde = { version = "^1.0.85", features = ['derive'] }
futures = "0.3"

mvg = {path="../mvg", features=["serde-serialize"]}
zip-or-dir = {path="../zip-or-dir"}
braidz-types = {path="../braidz-types"}
braidz-parser = {path="../braidz-parser"}

[profile.release]  # Attempts to minimize file size
lto = true
opt-level = 'z'
