[package]
name = "flydra2"
version = "0.20.29"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[lib]
path = "src/flydra2.rs"

[build-dependencies]
walkdir = { version = "2.2.5", optional = true }
includedir_codegen = { version = "0.5", optional = true }

[dependencies]
log = "0.4.8"
structopt = "0.3"
hdrhistogram = "7.1.0"
failure = "0.1.2"
failure_derive = "0.1.2"
parking_lot = "0.11"
crossbeam-channel = "0.5"
futures = "0.3"
pin-project = "0.4.0"
csv = "1.1"
chrono = "0.4.6"
serde = {version="^1.0", features=["derive"]}
serde_json = "1.0.29"
serde_yaml = "^0.8"
toml = "0.5"
nalgebra = { version = "0.23", features = ["serde-serialize"] }
ncollide3d = "0.26"
alga = "0.9"
configure = "0.1.1"
itertools = "0.8"
http = "0.2"
tower-service = "0.3.0"
hyper = {version="0.14", features=["tcp","server","http1","stream"]}
tokio = {version="1.0", default-features=false, features=["macros","rt","rt-multi-thread","sync","time"]}
stream-cancel = "0.7"
includedir = { version = "0.5", optional = true }
tempdir = "^0.3"
phf = { version = "0.7.23", optional = true }
env_logger = "0.8"
libflate = "0.1"
zip = { version = "0.5", default-features = false, features=["time"] }
walkdir = "2.2"

braidz-types = {path="../braidz-types"}
datetime-conversion = {path="../datetime-conversion"}
mvg = {path="../mvg"}
flydra-mvg = {path="../flydra-mvg"}
http-video-streaming-types = {path="../http-video-streaming/http-video-streaming-types"}
flydra-types = {path="../flydra-types"}
adskalman = "0.4"
tracking = {path="../tracking"}
groupby = {path="../groupby"}
pretty-print-nalgebra = {git="https://github.com/strawlab/pretty-print-nalgebra", rev="a5536f9a0f339d075a8d9f1edb2d387ec231ac6a"}
nalgebra-mvn = "0.5"
iana-time-zone = "0.1"
withkey = {path="../withkey"}
crossbeam-ok = {path="../crossbeam-ok"}
strand-cam-csv-config-types = {path="../strand-cam-csv-config-types"}
zip-or-dir = {path="../zip-or-dir"}

[dev-dependencies]
tempfile = "3"
fs_extra = "1.1"
approx = "0.4"
download-verify = {path="../download-verify"}

[features]
default = ["full-3d", "bundle_files"]

# must pick one of the following two:
full-3d = []
flat-3d = []

# must pick one of the following two:
bundle_files = ["walkdir", "includedir_codegen", "includedir", "phf"]
serve_files = []

braid = []

backtrace = ["zip-or-dir/backtrace"]
