[package]
name = "braidz-parser"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
serde_json = "1.0"
serde_yaml = "0.8"
csv = "1.1"
libflate = "0.1"
zip = { version = "0.5", default-features = false, features=["deflate", "time"] }
chrono = "0.4"
serde-xml-rs = "0.3.0"
hdrhistogram = "7.1"
base64 = "0.12"

csv-eof = {path="../csv-eof"}
braidz-types = {path="../braidz-types"}
flydra-types = {path="../flydra-types"}
flydra-mvg = {path="../flydra-mvg"}
zip-or-dir = {path="../zip-or-dir"}

[dev-dependencies]
env_logger = "0.8"
download-verify = {path="../download-verify"}
