[package]
name = "dc1394"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
libdc1394-sys = "0.2"
log = "0.4"
thiserror = "1.0"

[dev-dependencies]
env_logger = "0.8"
