[package]
name = "fmf-cli"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
autobins = false
edition = "2018"

[[bin]]
name = "fmf"
path = "src/fmf-cli.rs"

[dependencies]
log = "0.4"
env_logger = "0.8"
structopt = "0.3"
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
glob = "0.3"
image = "0.22"

machine-vision-formats = { path = "../../machine-vision-formats" }
timestamped-frame = {path="../../timestamped-frame"}
fmf = {path=".."}
convert-image = { path = "../../convert-image" }
basic-frame = { path = "../../basic-frame" }

webm = {version="1", optional=true}
webm-writer = { path = "../../webm-writer"}
ci2-remote-control = { path = "../../ci2-remote-control"}

nvenc = {path="../../nvenc",optional=true}

[features]
import-webm = ["webm"]
nv-h264 = ["nvenc"]
