[mainbrain]
# cal_fname = "blah.xml"
output_base_dirname = "DATA"
http_api_server_addr = "127.0.0.1:33333"
model_server_addr = "0.0.0.0:8397"
lowlatency_camdata_udp_addr = "127.0.0.1:7777"
save_empty_data2d = true

[[cameras]]
name = "Basler-40058153"
