[package]
name = "http-video-streaming"
version = "0.1.0"
authors = ["strawlab"]
edition = "2018"

[dependencies]
failure = "0.1"
bui-backend = {version="0.11", default-features = false}
bui-backend-types = "0.8"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.6"
hyper = "0.14"
serde_json = "1.0"
futures = "0.3"
parking_lot = "0.11"
crossbeam-channel = "0.5"
convert-image = {path = "../convert-image"}
log = "0.4"
machine-vision-formats = { path = "../machine-vision-formats" }
http-video-streaming-types = {path = "http-video-streaming-types"}
thread-control = "0.1.2"
