[package]
name = "strandcam-cabi"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[lib]
name = "strandcam"
crate-type = ["cdylib"]

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
strand-cam = {path="../../strand-cam", default-features = false, features=["bundle_files", "plugin-process-frame", "checkercal", "image_tracker", "imtrack-absdiff", "cfg-pt-detect-src-prefs"]}
plugin-defs = {path="../../plugin-defs"}
ipp-sys = "0.4.4" # Just so we can specify features

[build-dependencies]
cbindgen = "=0.8.2"
plugin-defs = {path="../../plugin-defs"}

[features]
backend_pyloncxx = ["strand-cam/backend_pyloncxx"]
backend_dc1394 = ["strand-cam/backend_dc1394"]
