[package]
name = "ci2-pyloncxx"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"
chrono = "0.4"
parking_lot = "0.11"
ci2 = { path = "../ci2" }
pylon-cxx = "0.1.0"
machine-vision-formats = { path = "../machine-vision-formats" }
timestamped-frame = { path = "../timestamped-frame" }
